index/urls.py
from django.urls import path

from . import views
app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.result, name='result'),
]

movies/urls.py
from django.urls import path

from . import views
app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.result, name='result'),
]

recinfo/urls.py
from django.urls import include, path
from . import views


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [ 
    path('', views.index, name='index'),
    path('movies/', include('movies.urls')), 
    path('index/', include('index.urls')),
]\
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/models.py
from django.db import models

# Create your models here.

movies/models.py
from django.db import models

# Create your models here.

index/views.py
from django.shortcuts import render 
import pprint
import serpscrap

# Create your views here.
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def result(request):
    
    keywords = ['example']
    
    config = serpscrap.Config()
    config.set('scrape_urls', False)
    
    scrap = serpscrap.SerpScrap()
    scrap.init(config=config.get(), keywords=keywords)
    results = scrap.run()
    
    for result in results:
        pprint.pprint(result)
       
    return HttpResponse("Hello, world. You're at the polls index.")

movies/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
import re
import requests

def index(request):
    context = {'description':'NULL'}
    return render(request, 'movies/index.html', context)

def result(request):
    url = "https://www.whatismymovie.com/results?"
    html = requests.get(url,params={'text':request.GET['movie_description']}).text
    regex = r"<a\s*href=[\"']item\?item=[0-9]*[\"']>.*?<\/a>" 
    regex_image = r"src='"
    html = re.sub(regex_image, "class='resize' src='https://www.whatismymovie.com", html)
    matches = re.findall(regex, html)
    
    pairmatches=[]
    dict={}
    for i,match in enumerate(matches):
        if i%2==0:
            dict={}
            dict['movie_name']=match
        else:
            dict['movie_image']=match
            pairmatches.append(dict)
    context = {'results':pairmatches}
    return render(request, 'movies/result.html', context)

recinfo/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from . import settings

def index(request):
    apps=[app for app in settings.INSTALLED_APPS if not app.startswith("django.")]
    apps_dict=[]
    for i,app in enumerate(apps):
        app_dict={}
        _app_=app.split(".")
        exec("from "+_app_[0]+"."+_app_[1]+" import "+_app_[2])
        app_dict["name"]=(eval(_app_[2]+".name"))
        app_dict["description"]=(eval(_app_[2]+".description"))
        app_dict["image"]=(eval(_app_[2]+".image"))
        app_dict["image_caption"]=(eval(_app_[2]+".image_caption"))
        app_dict["body"]=(eval(_app_[2]+".body"))
        apps_dict.append(app_dict)
    context = {'apps':apps_dict}
    return render(request, 'recinfo/index.html', context)

index/templates/index/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{tittle}}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            a {text-decoration: none;color: black;}
            * {
            box-sizing: border-box;
            }
            /* Style the body */
            body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
            }
            /* Header/logo Title */
            .header {
            padding: 80px;
            text-align: center;
            background: #1abc9c;
            color: white;
            }
            /* Increase the font size of the heading */
            .header h1 {
            font-size: 40px;
            }
            /* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
            .navbar {
            overflow: hidden;
            background-color: #333;
            position: sticky;
            position: -webkit-sticky;
            top: 0;
            }
            /* Style the navigation bar links */
            .navbar a {
            float: left;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 20px;
            text-decoration: none;
            }
            /* Right-aligned link */
            .navbar a.right {
            float: right;
            }
            /* Change color on hover */
            .navbar a:hover {
            background-color: #ddd;
            color: black;
            }
            /* Active/current link */
            .navbar a.active {
            background-color: #666;
            color: white;
            }
            /* Column container */
            .row {  
            display: -ms-flexbox; /* IE10 */
            display: flex;
            -ms-flex-wrap: wrap; /* IE10 */
            flex-wrap: wrap;
            }
            /* Create two unequal columns that sits next to each other */
            /* Sidebar/left column */
            .side {
            -ms-flex: 30%; /* IE10 */
            flex: 30%;
            background-color: #f1f1f1;
            padding: 20px;
            }
            /* Main column */
            .main {   
            -ms-flex: 70%; /* IE10 */
            flex: 70%;
            background-color: white;
            padding: 20px;
            }
            /* Fake image, just for this example */
            .fakeimg {
            background-color: #aaa;
            width: 100%;
            padding: 20px;
            }
            /* Footer */
            .footer {
            padding: 20px;
            text-align: center;
            background: #ddd;
            }
            /* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
            @media screen and (max-width: 700px) {
            .row {   
            flex-direction: column;
            }
            }
            /* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
            @media screen and (max-width: 400px) {
            .navbar a {
            float: none;
            width: 100%;
            }
            }
        </style>
    </head>
    <body>
        <div class="header">
            
        </div>
        <div class="footer">
            <h2>Footer</h2>
        </div>
    </body>
</html>

movies/templates/movies/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{tittle}}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            a {text-decoration: none;color: black;}
            * {
            box-sizing: border-box;
            }
            /* Style the body */
            body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
            }
            /* Header/logo Title */
            .header {
            padding: 80px;
            text-align: center;
            background: #1abc9c;
            color: white;
            }
            /* Increase the font size of the heading */
            .header h1 {
            font-size: 40px;
            }
            /* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
            .navbar {
            overflow: hidden;
            background-color: #333;
            position: sticky;
            position: -webkit-sticky;
            top: 0;
            }
            /* Style the navigation bar links */
            .navbar a {
            float: left;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 20px;
            text-decoration: none;
            }
            /* Right-aligned link */
            .navbar a.right {
            float: right;
            }
            /* Change color on hover */
            .navbar a:hover {
            background-color: #ddd;
            color: black;
            }
            /* Active/current link */
            .navbar a.active {
            background-color: #666;
            color: white;
            }
            /* Column container */
            .row {  
            display: -ms-flexbox; /* IE10 */
            display: flex;
            -ms-flex-wrap: wrap; /* IE10 */
            flex-wrap: wrap;
            }
            /* Create two unequal columns that sits next to each other */
            /* Sidebar/left column */
            .side {
            -ms-flex: 30%; /* IE10 */
            flex: 30%;
            background-color: #f1f1f1;
            padding: 20px;
            }
            /* Main column */
            .main {   
            -ms-flex: 70%; /* IE10 */
            flex: 70%;
            background-color: white;
            padding: 20px;
            }
            /* Fake image, just for this example */
            .fakeimg {
            background-color: #aaa;
            width: 100%;
            padding: 20px;
            }
            /* Footer */
            .footer {
            padding: 20px;
            text-align: center;
            background: #ddd;
            }
            /* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
            @media screen and (max-width: 700px) {
            .row {   
            flex-direction: column;
            }
            }
            /* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
            @media screen and (max-width: 400px) {
            .navbar a {
            float: none;
            width: 100%;
            }
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Data Retrival</h1>
            <p>Data Retrival Project</p>
        </div>
        <div class="navbar">
            <a href="/" class="active">Home</a>
        </div>
        <div class="row">
                        <div class="side">
                <h2>About Us</h2>
                <h5></h5>
                <!--<div class="fakeimg" style="height:200px;">Image</div>-->
                <p>Proyecto BUAP.</p>
                <h3>People</h3>
                <p>Juan Adolfo Bustillos Alatorre</p>
                <p>Bello Franquiz Orlando</p>
                <p>Campos Guevara Rogelio</p>
                <p>Ortega Santiago Brenda Sharonit</p>
                <p>Ingrid Camila Elias Magaña</p>
            </div>
            <div class="main">
                <h2>Movies</h2>
                <h3>Enter your movie description here:</h3>
                <form action="{% url 'movies:result'%}#result">
                    <textarea name="movie_description" id="movie_description" rows="10" cols="37">The cat was playing in the garden.</textarea>
                    <br>
                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
        <div class="footer">
            <h2></h2>
        </div>
    </body>
</html>

movies/templates/movies/result.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{tittle}}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            a {text-decoration: none;color: black;}
            * {
            box-sizing: border-box;
            }
            /* Style the body */
            body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
            }
            /* Header/logo Title */
            .header {
            padding: 80px;
            text-align: center;
            background: #1abc9c;
            color: white;
            }
            /* Increase the font size of the heading */
            .header h1 {
            font-size: 40px;
            }
            /* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
            .navbar {
            overflow: hidden;
            background-color: #333;
            position: sticky;
            position: -webkit-sticky;
            top: 0;
            }
            /* Style the navigation bar links */
            .navbar a {
            float: left;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 20px;
            text-decoration: none;
            }
            /* Right-aligned link */
            .navbar a.right {
            float: right;
            }
            /* Change color on hover */
            .navbar a:hover {
            background-color: #ddd;
            color: black;
            }
            /* Active/current link */
            .navbar a.active {
            background-color: #666;
            color: white;
            }
            /* Column container */
            .row {  
            display: -ms-flexbox; /* IE10 */
            display: flex;
            -ms-flex-wrap: wrap; /* IE10 */
            flex-wrap: wrap;
            }
            /* Create two unequal columns that sits next to each other */
            /* Sidebar/left column */
            .side {
            -ms-flex: 30%; /* IE10 */
            flex: 30%;
            background-color: #f1f1f1;
            padding: 20px;
            }
            /* Main column */
            .main {   
            -ms-flex: 70%; /* IE10 */
            flex: 70%;
            background-color: white;
            padding: 20px;
            }
            /* Fake image, just for this example */
            .fakeimg {
            background-color: #aaa;
            width: 100%;
            padding: 20px;
            }
            /* Footer */
            .footer {
            padding: 20px;
            text-align: center;
            background: #ddd;
            }
            /* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
            @media screen and (max-width: 700px) {
            .row {   
            flex-direction: column;
            }
            }
            /* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
            @media screen and (max-width: 400px) {
            .navbar a {
            float: none;
            width: 100%;
            }
            }
            /* DivTable.com */
            .divTable{
            display: table;
            width: 100%;
            }
            .divTableRow {
            display: table-row;
            }
            .divTableHeading {
            background-color: #EEE;
            display: table-header-group;
            }
            .divTableCell, .divTableHead {
            display: table-cell;
            padding: 3px 10px;
            }
            .divTableHeading {
            background-color: #EEE;
            display: table-header-group;
            font-weight: bold;
            }
            .divTableFoot {
            background-color: #EEE;
            display: table-footer-group;
            font-weight: bold;
            }
            .divTableBody {
            display: table-row-group;
            }
            .resize {
            width: 200px;
            height: auto;
            }
            .resize {
            width: 150;
            height: auto;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Data Retrival</h1>
            <p>Data Retrival Project</p>
        </div>
        <div class="navbar">
            <a href="/" class="active">Home</a>
        </div>
        <div class="row">
                        <div class="side">
                <h2>About Us</h2>
                <h5></h5>
                <!--<div class="fakeimg" style="height:200px;">Image</div>-->
                <p>Proyecto BUAP.</p>
                <h3>People</h3>
                <p>Juan Adolfo Bustillos Alatorre</p>
                <p>Bello Franquiz Orlando</p>
                <p>Campos Guevara Rogelio</p>
                <p>Ortega Santiago Brenda Sharonit</p>
                <p>Ingrid Camila Elias Magaña</p>
            </div>
            <div class="main">
                <h2>Movies</h2>
                <h3>Enter your movie description here:</h3>
                <form action="{% url 'movies:result'%}#result">
                    <textarea name="movie_description" id="movie_description" rows="10" cols="37">
                    The cat was playing in the garden.</textarea>
                    <br>
                    <input type="submit" value="Submit">
                </form>
                <h3 id="result">Result:</h3>
                <div class="divTable">
                    <div class="divTableBody">
                        {% for result in results %} 
                        <div class="divTableRow">
                            <div class="divTableCell">&nbsp;{{result.movie_name|safe}}</div>
                            <div class="divTableCell">{{result.movie_image|safe}}</div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="footer">
                <h2></h2>
            </div>
        </div>
    </body>
</html>

recinfo/templates/recinfo/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{tittle}}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            a {text-decoration: none;color: black;}
            * {
            box-sizing: border-box;
            }
            /* Style the body */
            body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
            }
            /* Header/logo Title */
            .header {
            padding: 80px;
            text-align: center;
            background: #1abc9c;
            color: white;
            }
            /* Increase the font size of the heading */
            .header h1 {
            font-size: 40px;
            }
            /* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
            .navbar {
            overflow: hidden;
            background-color: #333;
            position: sticky;
            position: -webkit-sticky;
            top: 0;
            }
            /* Style the navigation bar links */
            .navbar a {
            float: left;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 20px;
            text-decoration: none;
            }
            /* Right-aligned link */
            .navbar a.right {
            float: right;
            }
            /* Change color on hover */
            .navbar a:hover {
            background-color: #ddd;
            color: black;
            }
            /* Active/current link */
            .navbar a.active {
            background-color: #666;
            color: white;
            }
            /* Column container */
            .row {  
            display: -ms-flexbox; /* IE10 */
            display: flex;
            -ms-flex-wrap: wrap; /* IE10 */
            flex-wrap: wrap;
            }
            /* Create two unequal columns that sits next to each other */
            /* Sidebar/left column */
            .side {
            -ms-flex: 30%; /* IE10 */
            flex: 30%;
            background-color: #f1f1f1;
            padding: 20px;
            }
            /* Main column */
            .main {   
            -ms-flex: 70%; /* IE10 */
            flex: 70%;
            background-color: white;
            padding: 20px;
            }
            /* Fake image, just for this example */
            .fakeimg {
            background-color: #aaa;
            width: 100%;
            padding: 20px;
            }
            /* Footer */
            .footer {
            padding: 20px;
            text-align: center;
            background: #ddd;
            }
            /* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
            @media screen and (max-width: 700px) {
            .row {   
            flex-direction: column;
            }
            }
            /* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
            @media screen and (max-width: 400px) {
            .navbar a {
            float: none;
            width: 100%;
            }
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Data Retrival</h1>
            <p>Data Retrival Project</p>
        </div>
        <div class="navbar">
            <a href="#" class="active">Home</a>
        </div>
        <div class="row">
            <div class="side">
                <h2>About Us</h2>
                <h5></h5>
                <!--<div class="fakeimg" style="height:200px;">Image</div>-->
                <p>Proyecto BUAP.</p>
                <h3>People</h3>
                <p>Juan Adolfo Bustillos Alatorre</p>
                <p>Bello Franquiz Orlando</p>
                <p>Campos Guevara Rogelio</p>
                <p>Ortega Santiago Brenda Sharonit</p>
                <p>Ingrid Camila Elias Magaña</p>
            </div>
            <div class="main">
                {% load static %}
                {% for app in apps%}
                {% with app.name|add:":index" as href_url %}
                <a href="{% url href_url %}">
                {% endwith %}
                    <h2>{{app.name}}</h2> 
                </a>
                <h5>{{app.description}}</h5>
                <p>{{app.image_caption}}</p>
                <p>{{app.body}}</p>
                <br>
                 {% endfor %}
            </div>
        </div>
        <div class="footer">
            <h2></h2>
        </div>
    </body>
</html>